CREATE TABLE IF NOT EXISTS `subscription`
(
    `id`
        INT
        NOT
            NULL
        AUTO_INCREMENT
        PRIMARY
            KEY,
    `email`
        VARCHAR,
    `first_name`
        VARCHAR,
    `gender`
        VARCHAR,
    `date_of_birth`
        LONG,
    `consent_subscribe`
        BOOLEAN,
    `executed`
        BOOLEAN,
    `created_at`
        LONG
);
